services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Platino@1901
      MYSQL_DATABASE: hotel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app

volumes:
  db_data:



      